### ISSUE TITLE
javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by Luozuanshi** [asleepyfish/chatgpt#1]
在使用该工具类的时候跑出来一下错误
OpenAiUtils.createCompletion("docker 命令")

javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

大概的意思是没有使用ssl证书，请问如何配置

**Comment by asleepyfish** [comment]
不需要使用ssl，检查下面几个点是否配置好。
1.申请到chatGPT api keys且在配置文件中填写正确
2.启动类上加@EnableChatGPT注解
3.测试代码使用@SpringBootTest来作为加载spring bean

**Comment by asleepyfish** [comment]
> 在使用该工具类的时候跑出来一下错误
> 
> OpenAiUtils.createCompletion("docker 命令")
> 
> 
> 
> javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 
> 
> 
> 大概的意思是没有使用ssl证书，请问如何配置

不需要使用ssl，检查下面几个点是否配置好。
1.申请到chatGPT api keys且在配置文件中填写正确
2.启动类上加@EnableChatGPT注解
3.测试代码使用@SpringBootTest来作为加载spring bean

**Comment by Luozuanshi** [comment]
感谢您的回复。我明天确认一下
我记着启动类加了注解
配置文件也读取到了



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 14, 2023 02:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [asleepyfish/chatgpt] javax.net.ssl.SSLException (Issue #1)




  
在使用该工具类的时候跑出来一下错误
 
OpenAiUtils.createCompletion("docker 命令")
 
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 
大概的意思是没有使用ssl证书，请问如何配置
  
不需要使用ssl，检查下面几个点是否配置好。
 1.申请到chatGPT api keys且在配置文件中填写正确
 ***@***.***注解
 ***@***.***来作为加载spring bean
