### ISSUE TITLE
报错问题反馈

### ISSUE THREAD

**Issue by ex-xuzhihong001** [asleepyfish/chatgpt#11]
出现了这个错误，能帮忙看下么
[java.io.IOException: unexpected end of stream on https://api.openai.com/..., java.io.IOException: unexpected end of stream on https://api.openai.com/...]
2023-05-22 18:30:08.079 [scheduling-1] ERROR i.g.a.service.OpenAiProxyService - answer failed 1 times, the error message is: java.io.IOException: unexpected end of stream on https://api.openai.com/...

**Comment by asleepyfish** [comment]
> 出现了这个错误，能帮忙看下么 [java.io.IOException: unexpected end of stream on https://api.openai.com/..., java.io.IOException: unexpected end of stream on https://api.openai.com/...] 2023-05-22 18:30:08.079 [scheduling-1] ERROR i.g.a.service.OpenAiProxyService - answer failed 1 times, the error message is: java.io.IOException: unexpected end of stream on https://api.openai.com/...

看起来像是对话的流异常中断，多尝试几次，或者是更换更新的jdk版本和代理等。
