### ISSUE TITLE
请问在流返回时乱码的问题该如何解决

### ISSUE THREAD

**Issue by xiayana** [asleepyfish/chatgpt#12]
![584672fca9f02c8dbc93da15a9cc4de1](https://github.com/asleepyfish/chatgpt/assets/40882709/e07032a8-cb81-47b0-a740-8be181da4e19)

**Comment by asleepyfish** [comment]
> ![584672fca9f02c8dbc93da15a9cc4de1](https://user-images.githubusercontent.com/40882709/240875985-e07032a8-cb81-47b0-a740-8be181da4e19.png)

看一下[https://github.com/asleepyfish/chatgpt-demo](https://github.com/asleepyfish/chatgpt-demo)，里面是结合SpringBoot的demo，看一下流式输出那里。
