### ISSUE TITLE
代理主机的问题

### ISSUE THREAD

**Issue by csyeqing** [asleepyfish/chatgpt#13]
我自己单独写的程序调用openai的API一切正常，api的URL，api.openai.com换成腾讯云的云函数主机就可以了。但是我用你的这个依赖，代理主机也是写的我这个腾讯云的云函数主机，使用的时候，报错：
 i.g.a.service.OpenAiProxyService : answer failed 1 times, the error message is: java.io.IOException: Unexpected response code for CONNECT: 400

**Comment by csyeqing** [comment]
> 我自己单独写的程序调用openai的API一切正常，api的URL，api.openai.com换成腾讯云的云函数主机就可以了。但是我用你的这个依赖，代理主机也是写的我这个腾讯云的云函数主机，使用的时候，报错： i.g.a.service.OpenAiProxyService : answer failed 1 times, the error message is: java.io.IOException: Unexpected response code for CONNECT: 400

我用wireshark拦截了一下本地请求，发现你的依赖发出了api.openai.com的请求，这就奇怪了，既然写了代理主机，为什么还会向api.openai.com发请求？

**Comment by asleepyfish** [comment]
> Unexpected response code for CONNECT: 400

你的代理有问题，400说明是不完整的请求。但是这种情况一般多调用几次会有效果。把错误重试次数调大一些。
