### ISSUE TITLE
请问如何在流传输过程中主动停止这次响应呢

### ISSUE THREAD

**Issue by xiayana** [asleepyfish/chatgpt#14]
如题

**Comment by GuoXiaobai289** [comment]
兄弟，麻烦问问，你的代理是咋弄的

**Comment by xiayana** [comment]
> 兄弟，麻烦问问，你的代理是咋弄的

我是在idea vm options 里面加的代理，然后本地开梯子就行了，  部署的话 我们服务本身就在国外。

**Comment by asleepyfish** [comment]
> 如题

如果你有前端，调用后端的流式输出方法，那么发起的http请求，可以前端主动中断这次请求，这种方法因为后端应用的调用已产生，所以后端依然会完成本次调用。
还有一种方法是调用后端流式接口的时候，记录本次会话的response，比如记录在Map<String, HttpServletResponse>中，其中key是会话的id，前端应该会针对不同的会话有不同的会话id，可以参考我做的界面[http://chatgpt.alpacos.cn](http://chatgpt.alpacos.cn)，然后前端点击停止的时候带着会话id找到response，然后执行response.getOutputStream().close()。这样可以直接在后端直接停止。
