### ISSUE TITLE
好像还不支持多个key轮询？

### ISSUE THREAD

**Issue by harryyhy** [asleepyfish/chatgpt#17]

**Comment by asleepyfish** [comment]
> _No description provided._

此依赖提供基本功能，复杂的功能实现，此依赖不提供。
当然扩展实现多个key轮询也很简单，在你的项目中引入此依赖，使用自定义扩展的openAiProxyService，初始化项目时，构建全局多个key和service的关系，再写一个策略，调用服务时自定义获取key对应的service的策略就好了。
