### ISSUE TITLE
无法流式返回

### ISSUE THREAD

**Issue by song782360037** [asleepyfish/chatgpt#19]
使用baseUrl来反向代理，不通过proxy的时候，无法流式返回结果

**Comment by asleepyfish** [comment]
> 使用baseUrl来反向代理，不通过proxy的时候，无法流式返回结果

看看第四节，我修改baseUrl且不使用代理是可以流式返回的。如果看完按照操作还不行的话，可以把代码发给我给你调试一下。

**Comment by song782360037** [comment]
我感觉很奇怪，就是有时候可以，有时候又不可以，我刚刚试了下又可以了，不知道为什么。
