### ISSUE TITLE
这个可以保持同一个会话吗？

### ISSUE THREAD

**Issue by 7757** [asleepyfish/chatgpt#2]
目前没有发现可以连续对话

**Comment by asleepyfish** [comment]
> 目前没有发现可以连续对话

api版本的官方暂不提供上下文能力，可以去web体验

**Comment by 7757** [comment]
为什么不是最新版的

**Comment by asleepyfish** [comment]
> 为什么不是最新版的

是API里最新的模型了，但是和网页端的模型不是一个，后面看啥时候官方提供API最新模型了再说

**Comment by asleepyfish** [comment]
> 目前没有发现可以连续对话

最新版已经支持连续对话
