### ISSUE TITLE
多轮会话的缓存问题

### ISSUE THREAD

**Issue by lcky666** [asleepyfish/chatgpt#20]
目前多轮会话根据传参user为Key，使用com.google.common.cache 储存在本地，集群部署后缓存无法共享导致多轮会话信息丢失。
能否在配置中支持redis等中间件来代替本地缓存？

**Comment by asleepyfish** [comment]
> 目前多轮会话根据传参user为Key，使用com.google.common.cache 储存在本地，集群部署后缓存无法共享导致多轮会话信息丢失。 能否在配置中支持redis等中间件来代替本地缓存？

 其实这个东西想过，但是因为本api为最基础的api，所以没有考虑集成太多中间件，所以没有使用redis，但是暴露了获取和设置cache的接口方法，可以自行对cache的内容做修改，如果是单机，应该可以自由通过这两个cache相关方法把数据保存到redis或者数据库中。如果是集群下，那可能需要考虑一下机器间的同步问题了。当然fork项目直接把cache替换成redis也是可以的。

**Comment by asleepyfish** [comment]
> 目前多轮会话根据传参user为Key，使用com.google.common.cache 储存在本地，集群部署后缓存无法共享导致多轮会话信息丢失。 能否在配置中支持redis等中间件来代替本地缓存？

简单点无脑一点的就是自己把会话的上下文记录下来存到redis或者数据库里，下一次请求，先把上下文拿到先set到cache里，然后再调用。

**Comment by lcky666** [comment]
收到，有时间我会把关于redis override的代码fork上
