### ISSUE TITLE
关于查询账单和订阅部分的bug

### ISSUE THREAD

**Issue by Autunomy** [asleepyfish/chatgpt#21]
目前官网好像对于查询使用量的api进行修改，其中的token使用的是另一个session key而不是在配置文件中配置的api key，所以在使用OpenAiUtils.billingUsage()方法的时候可能需要对token进行修改。新版的session key可以从官网中进行一次查询而获取到
![image](https://github.com/asleepyfish/chatgpt/assets/73972467/5a31a38e-4325-429f-b0e5-8b5e1f65dad8)

作者大大可以对这个接口进行一个重新适配吗

**Comment by asleepyfish** [comment]
> 目前官网好像对于查询使用量的api进行修改，其中的token使用的是另一个session key而不是在配置文件中配置的api key，所以在使用OpenAiUtils.billingUsage()方法的时候可能需要对token进行修改。新版的session key可以从官网中进行一次查询而获取到 ![image](https://user-images.githubusercontent.com/73972467/257530184-5a31a38e-4325-429f-b0e5-8b5e1f65dad8.png)
> 
> 作者大大可以对这个接口进行一个重新适配吗

请问你说的这个session key是通过什么获取的？抓包？还是调用接口。

**Comment by Autunomy** [comment]
直接访问这个页面 f12调试打开之后 点击usage就可以看见如图的请求以及红框中的session key

**Comment by asleepyfish** [comment]
> 直接访问这个页面 f12调试打开之后 点击usage就可以看见如图的请求以及红框中的session key

你这种属于抓包了，原则上使用API方式调用OpenAI服务，就不考虑抓包那一套了。

**Comment by Autunomy** [comment]
ok 那就可以关闭当前issue了

**Comment by asleepyfish** [comment]
> Reference in new

好的，主要是这个抓包，还需要登录账号和密码，登录账号密码的时候有时会报cloudflare的验证，登录账号密码这一套github上有demo，是用python做的，但是缺点也是有的，就是很不稳定，不如API调用稳定。
