### ISSUE TITLE
proxy需要auth验证账号密码怎么办

### ISSUE THREAD

**Issue by lxhj** [asleepyfish/chatgpt#23]
SOCKS : authentication failed
如何能填入账号密码呢？

**Comment by asleepyfish** [comment]
> SOCKS : authentication failed 如何能填入账号密码呢？

请附上报错方法，具体的操作，以及出现的现象

**Comment by lxhj** [comment]
> > SOCKS : authentication failed 如何能填入账号密码呢？
> 
> 请附上报错方法，具体的操作，以及出现的现象

代理有账号和密码
![image](https://github.com/asleepyfish/chatgpt/assets/5977779/7250344d-524c-4ece-9e98-064b09b4619f)

![image](https://github.com/asleepyfish/chatgpt/assets/5977779/9641ab32-f9b6-4e14-b43e-c8d545bb3a2a)

![image](https://github.com/asleepyfish/chatgpt/assets/5977779/9f649da9-8dff-42c7-b938-323702644876)

SOCKS的连接部分，应该可以设置auth账号和密码的，默认是无。

**Comment by lxhj** [comment]
![image](https://github.com/asleepyfish/chatgpt/assets/5977779/c24a0233-41a1-474c-880e-d25b295370e2)
代理部分前面加入

**Comment by asleepyfish** [comment]
> failed

这个地方修改差不多是这样的，你可以先fork代码先改着，后面有空我会同步
![image](https://github.com/asleepyfish/chatgpt/assets/46968917/4bc50eff-9c9e-4d7b-9822-1b809c4dd8c3)

**Comment by lxhj** [comment]
> > failed
> 
> 这个地方修改差不多是这样的，你可以先fork代码先改着，后面有空我会同步 ![image](https://user-images.githubusercontent.com/46968917/258095407-4bc50eff-9c9e-4d7b-9822-1b809c4dd8c3.png)

是的，然后我发现作者的项目拉下来，通过本地jar包引入，会缺少一些包，比如
![image](https://github.com/asleepyfish/chatgpt/assets/5977779/c8809618-6b08-4c8c-b9a5-50ed2a088d2e)
不知道正确的打包方式选哪个？

另外调用其他图片处理接口时候项目会报错，查询了下问题是okhttp版本冲突问题，可以参加解决
![image](https://github.com/asleepyfish/chatgpt/assets/5977779/eca4e4e8-0599-4cc8-8b51-9103173305d0)

**Comment by asleepyfish** [comment]
> > > failed
> 
> > 
> 
> > 这个地方修改差不多是这样的，你可以先fork代码先改着，后面有空我会同步 ![image](https://user-images.githubusercontent.com/46968917/258095407-4bc50eff-9c9e-4d7b-9822-1b809c4dd8c3.png)
> 
> 
> 
> 是的，然后我发现作者的项目拉下来，通过本地jar包引入，会缺少一些包，比如
> 
> ![image](https://github.com/asleepyfish/chatgpt/assets/5977779/c8809618-6b08-4c8c-b9a5-50ed2a088d2e)
> 
> 不知道正确的打包方式选哪个？
> 
> 
> 
> 另外调用其他图片处理接口时候项目会报错，查询了下问题是okhttp版本冲突问题，可以参加解决
> 
> ![image](https://github.com/asleepyfish/chatgpt/assets/5977779/eca4e4e8-0599-4cc8-8b51-9103173305d0)
> 
> 

把代码clone下来，然后看一下版本号记录一下，然后本地maven install，下载chatgpt-demo项目，把引入的chatgpt的版本换成刚才clone下来的版本号。依赖是可以引入的。如果版本有冲突，就exclude一下，使用你想用的且不会与其他jar包冲突的版本即可。

**Comment by asleepyfish** [comment]
> > > SOCKS : authentication failed 如何能填入账号密码呢？
> > 
> > 
> > 请附上报错方法，具体的操作，以及出现的现象
> 
> 代理有账号和密码 ![image](https://user-images.githubusercontent.com/5977779/257997165-7250344d-524c-4ece-9e98-064b09b4619f.png)
> 
> ![image](https://user-images.githubusercontent.com/5977779/257997332-9641ab32-f9b6-4e14-b43e-c8d545bb3a2a.png)
> 
> ![image](https://user-images.githubusercontent.com/5977779/257997735-9f649da9-8dff-42c7-b938-323702644876.png)
> 
> SOCKS的连接部分，应该可以设置auth账号和密码的，默认是无。

1.3.3版本解决，通过自定义client，实现输入代理账号密码功能。
