### ISSUE TITLE
system消息

### ISSUE THREAD

**Issue by huchenghao** [asleepyfish/chatgpt#24]
请问，怎么发送role为system类的消息？RoleEnum.SYSTEM

**Comment by asleepyfish** [comment]
> 请问，怎么发送role为system类的消息？RoleEnum.SYSTEM

调用createStreamChatCompletion方法中入参带ChatCompletionRequest对象的重载方法，messages字段中ChatMessage类中可以定义role为system。

**Comment by huchenghao** [comment]
> 
你好作者，有system和user两种角色一起发送的方法吗？

**Comment by huchenghao** [comment]
感谢作者，已找到方法
