### ISSUE TITLE
救救孩子

### ISSUE THREAD

**Issue by zhaowendao2023** [asleepyfish/chatgpt#26]
大佬，在用你给的demo没有任何问题，但我自己的所以项目都报同一个错误
`Error creating bean with name 'okHttpClient' defined in io.github.asleepyfish.config.ChatGPTAutoConfigure: Failed to instantiate [okhttp3.OkHttpClient]: Factory method 'okHttpClient' threw exception with message: javax/servlet/ServletOutputStream`
救救孩子吧

**Comment by asleepyfish** [comment]
> 大佬，在用你给的demo没有任何问题，但我自己的所以项目都报同一个错误 `Error creating bean with name 'okHttpClient' defined in io.github.asleepyfish.config.ChatGPTAutoConfigure: Failed to instantiate [okhttp3.OkHttpClient]: Factory method 'okHttpClient' threw exception with message: javax/servlet/ServletOutputStream` 救救孩子吧

当没自定义okHttpClient的时候会使用默认的构造，检查一下

**Comment by zhaowendao2023** [comment]
在引入servlet依赖之后才解决了，但我看大佬的demo里并没有引入，难道是Java或者idea自带，然后我用17版的JDK所以冲突了？还得多学习

**Comment by asleepyfish** [comment]
> 在引入servlet依赖之后才解决了，但我看大佬的demo里并没有引入，难道是Java或者idea自带，然后我用17版的JDK所以冲突了？还得多学习

我一直用的Java17没问题的
