### ISSUE TITLE
使用stream输出到web只输出一半

### ISSUE THREAD

**Issue by tianxiakeji** [asleepyfish/chatgpt#27]
在使用stream到web时，只输出了一半就停止了。有参数可以控制返回长度或者其它操作吗

**Comment by asleepyfish** [comment]
> 在使用stream到web时，只输出了一半就停止了。有参数可以控制返回长度或者其它操作吗

输出一半就停止有很多种情况，比如网络问题中断了，比如达到一个会话最大支持的token数了，看一下api里面的方法，有一个入参是对象的方法，可以控制每次请求token的长度。
