### ISSUE TITLE
能否提供在会话时间内清空所有问答数据的功能？

### ISSUE THREAD

**Issue by ruanzhijun** [asleepyfish/chatgpt#3]
如果回话时间很长，期间问的问题有可能答案会很长，很容易就把4096 tokens占满，This model's maximum context length is 4096 tokens

**Comment by asleepyfish** [comment]
> 如果回话时间很长，期间问的问题有可能答案会很长，很容易就把4096 tokens占满，This model's maximum context length is 4096 tokens

后续会考虑增加清除功能，你可以将会话时间修改成5min或者更低来作为过度方案。

**Comment by asleepyfish** [comment]
> > 如果回话时间很长，期间问的问题有可能答案会很长，很容易就把4096 tokens占满，This model's maximum context length is 4096 tokens
> 
> 后续会考虑增加清除功能，你可以将会话时间修改成5min或者更低来作为过度方案。

v1.1.1已修复
