### ISSUE TITLE
这个项目真的很棒，话说请问，可以额外加入这些设置到依赖里面吗？

### ISSUE THREAD

**Issue by congyujiang** [asleepyfish/chatgpt#30]
![屏幕截图 2023-12-12 212025](https://github.com/asleepyfish/chatgpt/assets/83690890/2b43717c-4264-4f23-b3d3-b5e0ae8e952a)

**Comment by asleepyfish** [comment]
> ![屏幕截图 2023-12-12 212025](https://private-user-images.githubusercontent.com/83690890/289871506-2b43717c-4264-4f23-b3d3-b5e0ae8e952a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzEwMTEsIm5iZiI6MTcwMzQ3MDcxMSwicGF0aCI6Ii84MzY5MDg5MC8yODk4NzE1MDYtMmI0MzcxN2MtNDI2NC00ZjIzLWIzZDMtYjVlMGFlOGU5NTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAyMTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODI0OGFiNDU1ZTQ1MTA5NDUxMmRjNDY1MzdhZTlkOWRiZjBlZDUxYzMzMThkMmQxMDBhOGM4M2RiZmUxNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BFWhpsffi1m-QU4c9f6MtqpDNtpY3TOPq1MeV7lo42g)

除了系统级提示消息基本上都有了

**Comment by asleepyfish** [comment]
> ![屏幕截图 2023-12-12 212025](https://private-user-images.githubusercontent.com/83690890/289871506-2b43717c-4264-4f23-b3d3-b5e0ae8e952a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTQyNzEsIm5iZiI6MTcwMzgxMzk3MSwicGF0aCI6Ii84MzY5MDg5MC8yODk4NzE1MDYtMmI0MzcxN2MtNDI2NC00ZjIzLWIzZDMtYjVlMGFlOGU5NTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAxMzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjkyNTJiMWY2YmJmNWRiOWQzYzI3OWMxZDIyNDZlOGRhZGI5ZjYxNjc2ODJkZjdmOGRlZDY4MTdiMjQ3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tbc9rAIn2fvEtTTpQ9eYVwOBQPBcEZdLyxdKVrmonzE)

1.3.6版本新增系统级提示、计算token及多token使用功能
