### ISSUE TITLE
免费的openai反向代理最好别用

### ISSUE THREAD

**Issue by HQ-Q** [asleepyfish/chatgpt#31]
免费的openai反向代理最好别用，这种反向代理服务存在的唯一原因就是盗用api-key

**Comment by asleepyfish** [comment]
> 免费的openai反向代理最好别用，这种反向代理服务存在的唯一原因就是盗用api-key

你是对的，但是对于仅学习用，没有自己代理，或者代理不稳定的，可以作为一个备选方式。
