### ISSUE TITLE
 实际使用发现时间会慢,源码发现是先阻塞接受所有消息再以流式返回

### ISSUE THREAD

**Issue by zhangfulei6521** [asleepyfish/chatgpt#33]
这部分我尝试去掉blockingForEach想实现api接收到立马返回给前端,但总是报错,空指针,或者别的.这部分能有颁发解决吗?本人小白,太深奥的也没看明白..   特此来请教作者大佬super.streamChatCompletion(chatCompletionRequest).doOnError(Throwable::printStackTrace).blockingForEach(chunk -> {
                    chunk.getChoices().stream().map(choice -> choice.getMessage().getContent())
                            .filter(Objects::nonNull).findFirst().ifPresent(o -> {
                                try {
                                    os.write(o.getBytes(Charset.defaultCharset()));
                                    os.flush();
                                } catch (Exception e) {
                                    throw new RuntimeException(e);
                                }
                            });
                    chunks.add(chunk);
                });

**Comment by asleepyfish** [comment]
> 这部分我尝试去掉blockingForEach想实现api接收到立马返回给前端,但总是报错,空指针,或者别的.这部分能有颁发解决吗?本人小白,太深奥的也没看明白..   特此来请教作者大佬super.streamChatCompletion(chatCompletionRequest).doOnError(Throwable::printStackTrace).blockingForEach(chunk -> {
> 
>                     chunk.getChoices().stream().map(choice -> choice.getMessage().getContent())
> 
>                             .filter(Objects::nonNull).findFirst().ifPresent(o -> {
> 
>                                 try {
> 
>                                     os.write(o.getBytes(Charset.defaultCharset()));
> 
>                                     os.flush();
> 
>                                 } catch (Exception e) {
> 
>                                     throw new RuntimeException(e);
> 
>                                 }
> 
>                             });
> 
>                     chunks.add(chunk);
> 
>                 });

实际上是实时返回的，后台用的sse，这里的os是外部传入的输出流对象，sse每打印一个字，输出流就会通过os输出到外面，所以实现的是实时输出，你看代码以为blocking，实际上就是通过里面的循环来持续输出的，每一个chunk就是几个文字，很多个chunk组合起来就是完整的问答，并不是说所有内容都输出才能返回。

**Comment by zhangfulei6521** [comment]
哦哦好的 谢谢~
