### ISSUE TITLE
连续对话会报错

### ISSUE THREAD

**Issue by zhoujuntop** [asleepyfish/chatgpt#4]
你好连续对话会报错
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/39981257/225245397-901cf52f-d885-4b7e-8e65-1c895dd6a4ee.png">

**Comment by asleepyfish** [comment]
> 你好连续对话会报错 <img alt="image" width="1275" src="https://user-images.githubusercontent.com/39981257/225245397-901cf52f-d885-4b7e-8e65-1c895dd6a4ee.png">

本地环境缺少SSL证书，可以采用以下几个方法试一试，
①下载证书，在代码里添加环境变量。
②可能你用的是1.8里面比较低的JDK版本，更新一下JDK试试吧。
③重装系统。
④换一台电脑环境。

**Comment by zhoujuntop** [comment]
解决了，jdk版本11高了
